### ISSUE TITLE
FALM 7.6 adds lots of extra section elements

### ISSUE THREAD

**Issue by JohnBergman** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#18]
For more details, refer to this thread on Our.umbraco.com
https://our.umbraco.org/projects/backoffice-extensions/falm-housekeeping/bugs-reports/86787-falm-76-adds-lots-of-extra-section-elements

After upgrading and running for a while, I noticed that a lot of additional nodes for "FALM" are created.

**Comment by afabri73** [comment]
Hi John,
see the attachments...this is what I see in my Umbraco Languages Folder.
- **wwwroot/Config/Lang**:
![config language folder](https://user-images.githubusercontent.com/6714121/29559797-58c74a54-8730-11e7-9585-1565d9166468.png)

- **wwwroot/Umbraco/Config/Lang**:
![umbraco config language folder](https://user-images.githubusercontent.com/6714121/29559813-6620aac4-8730-11e7-885b-4844408cb18a.png)

And this is the content of the en.xml, it.xml and en_us.xml files inside wwroot/Umbraco/Content/Lang folder:
![umbraco - en](https://user-images.githubusercontent.com/6714121/29559875-996ad814-8730-11e7-8476-afc934041393.png)

![umbraco - it](https://user-images.githubusercontent.com/6714121/29559887-a0f7a382-8730-11e7-81de-b7edc8bd11cd.png)

![umbraco - en_us](https://user-images.githubusercontent.com/6714121/29559892-a6e4b2a8-8730-11e7-9b37-8feb46e4f64a.png)

The content of these folders and these files are the same in my Umbraco v7.5+ and Umbraco v7.6+ installations.
I really don't understand why in your Umbraco website.
I tried my package into 4 different website (v7.5+ and v7.6+) and I haven't this problem.

Can you download the last version of the package and remove all FALM instances (check in the website folder and also in the DB) and reinstall it?
I don't know what to do, because I haven't this problem.

I look forward to your reply
Adriano

**Comment by JohnBergman** [comment]
In the version I have it appears that KeyMissing() always returns true in the InstallLanguageKey method (I reflectored the assembly that was installed).

I don't see the source in the repo for the HKLanguageInstaller class, perhaps there was a mismatch in the dll somewhere along the line?

**Comment by afabri73** [comment]
You can find the "HKLanguageInstaller class" into **/FALM/Housekeeping/Helpers/Installer.cs**

Soon I'll move it in the root folder of the project ("/FALM/Housekeeping/")

**Comment by JohnBergman** [comment]
I did a full removal of FALM like you suggested.  

After restarting, I noticed that the FALM in the backoffice sections shows up as [FALM], and in the tree, there is [MembersManager.TreeSection]; The title comes up as [sections_FALM]

It looks like there is still some sort of an issue that needs to be addressed.

I am running Umbraco 7.6.5

**Comment by afabri73** [comment]
oh...it is a mistake.
I'm trying a new functionality for umbraco members and I uploaded the new (wip) package instead of the correct one.
I have uploaded the correct package and updated the source project.

Sorry for the inconvenience.

**Comment by dnwhte** [comment]
Awesome @afabri73! Will it be available on Our soon?

**Comment by afabri73** [comment]
It is already on our.umbraco.org.

**Comment by JohnBergman** [comment]
I can confirm that this is fixed.
