### ISSUE TITLE
Not supported on 7.6

### ISSUE THREAD

**Issue by Elven11** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#25]
It seems that you replace all core DLLs with your own version, and therefore I lose things like RelatedLinks.
Please if possible update it to use latest Umbraco version, as your plugin seems like a great thing.

**Comment by afabri73** [comment]
:-O
You tell on NuGet...right?

**Comment by Elven11** [comment]
Yep on Nuget, if I am wrong, feel free to delete the thread, but I kept getting errors that RelatedLinks can't be found.

**Comment by afabri73** [comment]
This is my first time with NuGet and when I generate the package, I put all necessary (also references and assemblies) to run the project correctly.
I think this is the problem you have, because the current umbraco assemblies are v7.5.14
Can you help me to setup correctly the .nuspec file?
I attached my current .nuspec file for info.
[FALMHousekeeping.txt](https://github.com/FALM-Umbraco-Projects/FALM-Housekeeping-v7/files/1329612/FALMHousekeeping.txt)

Thank you for your help
