### ISSUE TITLE
Upon startup the FALM module adds another F.A.L.M. even though it already exists in the XML language file.

### ISSUE THREAD

**Issue by ghost** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#36]
Upon startup the FALM module adds another F.A.L.M. even though it already exists in the XML language file.

**Comment by afabri73** [comment]
Hi EmyXOR,
what umbraco version do you use and what FALM HK version did you installed?

However...try to remove all FALM HK versions and clean all FALM HK reference in the XML files.
Then re-install correct version of FALM HK for your Umbraco installation.

Adriano

**Comment by bjarnef** [comment]
@afabri73 the latest version of the package, it only support Umbraco 7.5+ so it doesn't need to modify core language files on startup - just add the additional keys in the `/App_Plugins/FALM/lang`
https://github.com/FALM-Umbraco-Projects/FALM-Housekeeping-v7/issues/34

It has been supported since Umbraco 7.3, so unless you want to support pre Umbraco 7.3 versions, it isn't necessary. In these language files you can also add the section language key.

**Comment by afabri73** [comment]
I already use my custom language files in the /App_Plugins/FALM/lang folder.
I think that there is a refuse from older version of FALM Housekeeping.

I re-checked all my project and I think that I must remove the "HkLanguageInstaller.CheckAndInstallLanguageActions();" when application start.

I try and if it is the problem, I'll republish the new version of my package

Thank you for the support.

**Comment by afabri73** [comment]
Yeah...It was the problem.
I removed it!!!

I'm updating the package on our.umbraco

Thank you again
