### ISSUE TITLE
cleanup users throws error because of FK_umbracoUserLogin_umbracoUser_id 

### ISSUE THREAD

**Issue by idseefeld** [FALM-Umbraco-Projects/FALM-Housekeeping-v7#46]
In Umbraco version 7.9.2 cleanup users throws error because of _**FK_umbracoUserLogin_umbracoUser_id**_ 
in case userid is in table _umbracoUserLogin_.

**Comment by afabri73** [comment]
Hi Dirk,
ok...this is very strange because I tried all functions before publish the package and I I haven't encountered problems.
I tested the package with this Umbraco versions:
Umbraco v7.6.13
Umbraco v7.7.13
Umbraco v7.8.1
Umbraco v7.9.2

Can you tell me which FALM version do you are using?
I'll try to do some test.
Keep in touch...I tell you something in the next days.

Thank you for the support.

**Comment by afabri73** [comment]
Ok Dirk,
I tested my FALM v7.7.1.0 with Umbraco v7.9.2 and I haven't problems.
In the attachments I send you the screenshot of what I've done.

![new user](https://user-images.githubusercontent.com/6714121/37895696-5f68228c-30e2-11e8-87f1-6aafe9ae87ab.png)
![falm - cleanup users](https://user-images.githubusercontent.com/6714121/37895701-64492774-30e2-11e8-8437-97b73117cf04.png)
![falm - user deleted](https://user-images.githubusercontent.com/6714121/37895705-67020bf2-30e2-11e8-869a-e9f5976d98c7.png)

Can you try to uninstall all FALM Housekeeping installed versions and reinstall the v7.7.1.0?
I look forward to your reply.

Adriano

**Comment by afabri73** [comment]
I close the issue in the meantime I waiting for your feedback.
I will reopen it as soon as I'll receive your message.

Adriano
